### ISSUE TITLE
Notebook is not able to parse valid raml

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [mulesoft/api-notebook#331]
Hi I am trying to create API client for a following RAML, 
http://api-portal.anypoint.mulesoft.com/onpositive/api/twitch-raml-api/twitch.raml

this file is parsed fine by API designer, API console and RAML java parser.

However notebooks are not able to create client for them with a following error: http://prntscr.com/3b0121

Regards,
Pavel

**Comment by sichvoge** [comment]
Seems to be more a RAML + parser issue. Closing it.
