### ISSUE TITLE
~ sign is not understood correctly

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [mulesoft/api-notebook#343]
Hi it seems that ~ partially  brokes api-notebooks
http://api-portal.anypoint.mulesoft.com/onpositive/api/linked-api/linkedIn.raml

Regards,
Pavel

**Comment by sichvoge** [comment]
I am closing that since I don't think we got very far here. Notebook relies on JavaScript as Blake mentions and nothing that is not syntactical correct should not be used.
