### ISSUE TITLE
When calling method https://api.twitter.com/1.1/saved_searches/destroy/{id} url parameter is ignored

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [mulesoft/api-notebook#363]
When calling method https://api.twitter.com/1.1/saved_searches/destroy/{id} url parameter is ignored. And notebook actually calls https://api.twitter.com/1.1/saved_searches/destroy/

RAML can be found at: http://api-portal.anypoint.mulesoft.com/onpositive/api/twitter-api/twitter.raml

Thanks in advance,
Pavel

**Comment by sichvoge** [comment]
seems more an issue of the RAML file.
