### ISSUE TITLE
Box API. The `client.folders.folderId(0).get()` line calls `https://api.box.com/2.0/folders/` URL

### ISSUE THREAD

**Issue by KonstantinSviridov** [mulesoft/api-notebook#376]
The `client.folders.folderId(0).get()` line calls `https://api.box.com/2.0/folders/` URL while it must call `https://api.box.com/2.0/folders/0`.

At the same time `client("/folders/0").get()` works fine and `client.folders.folderId(id).get()` works fine with `id!=0

Notebook
https://api-notebook.anypoint.mulesoft.com/notebooks#aa04b170788d39b36b68

PT Story
https://www.pivotaltracker.com/story/show/67847618

**Comment by sichvoge** [comment]
Seems to do the trick!
