### ISSUE TITLE
Could use a getting started guide

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-notebook#377]
After poking around for half an hour, I can't make anything work, so I guess a little "getting started" guide would be great.

Here is what I tried:

- Run: `grunt`
- Browse http://localhost:3000. A blank page titled `Manual Embedded Notebook Example` loads, the console shows:
```
ReferenceError: gistPersistencePlugin is not defined
Stack trace:
@http://localhost:3000/scripts/bundle.js line 30701 > eval:2:1
[141]</<@http://localhost:3000/scripts/bundle.js:30701:5
move@http://localhost:3000/scripts/bundle.js:40551:9
move/called</</<@http://localhost:3000/scripts/bundle.js:40535:20
[1]</</</async.each/</<@http://localhost:3000/scripts/bundle.js:118:25
only_once/<@http://localhost:3000/scripts/bundle.js:26:13
[159]</module.exports/script.onload@http://localhost:3000/scripts/bundle.js:33072:16
```
- Browse http://localhost:3000/embedded.html. Same error as before, except the page is titled `Embedded Notebook Example`.
- Browse http://localhost:3000/embed.html. A notebook shows up, no error in the console :dancers:  If I try then:
```javascript
API.createClient('test','http://localhost:8080/path/to/api.raml');
```
I'm greeted with:
```
ReferenceError: API is not defined
@http://localhost:3000/scripts/bundle.js line 32597 > eval:2:1 [151]</</</<@http://localhost:3000/scripts/bundle.js:32597:22 [10]</process.nextTick</<@http://localhost:3000/scripts/bundle.js:3560:21
```
:skull:
I'm clearly missing the point here, I can see that the pages, with their different titles, are trying to tell me something. But all in all, everything is very mysterious.

**Comment by blakeembrey** [comment]
Hey! Could you check out the `README.md` now? I've added some instructions.
