### ISSUE TITLE
API's with "-" in the resource name

### ISSUE THREAD

**Issue by takearun** [mulesoft/api-notebook#378]
Hi,

An API that I expose has a "-" in the resource name for example (/sportsbook-api/events)

API Notebook doesn't build the object structure because there's a -. Is there a way to override it?

Thanks,
Arun

**Comment by blakeembrey** [comment]
@takearun It should be working fine. Have you tried using the square bracket notation of JavaScript? `client.sportsbook-api` is not valid, you'll need to use `client['sportsbook-api']`. Let me know if this is still an issue.

**Comment by takearun** [comment]
Absolutely. Thank you so much.

Arun
