### ISSUE TITLE
API Notebook as a webapp

### ISSUE THREAD

**Issue by takearun** [mulesoft/api-notebook#379]
Hi,

I don't know node js or Grunt. Is there a way to deploy API Notebook as a webapp (tomcat preferred)?
If so, will it be possible to list the steps.

Really appreciate your help.

Thanks,
Arun

**Comment by blakeembrey** [comment]
@takearun I don't know Tomcat, but you're going to have to install Node and the dependencies to at least build the static assets of the project. From there, you can do whatever you need to with those assets. You technically don't need Node to run the project, just to build the assets.

**Comment by takearun** [comment]
Hi Blake,

Thank you for the quick answer.
I have installed Node on my local machine. I will try and expose it as a Webapp.

Having said that, I was expecting, API Notebook, like the API Console to be exposed as a webapp.

What I mean by that is, one RAML file to be given as an input to API Notebook and then for me to define a few notebooks. 
My API Developers should be able to access it, as a website and be able to play around with that. Passing their own client id/secret, that I provision them with.

Your installation instructions expects me to set client id and client secret in config/development.json. 
If that is the case, are you expecting API Developers to install this as a standalone application and use it?

Really appreciate your help.

Thanks,
Arun

**Comment by blakeembrey** [comment]
It can be exposed as a webapp perfectly fine, just build the project using `grunt build` and do what you wish with the built files. API Notebook does not consume one single RAML file, it can consume multiple RAMLs. You can inject client ids/client secrets dynamically, but you shouldn't be doing it by creating a ton of different webapp instances. The config is there for static keys, you can inject other keys with JavaScript (it's not well documented) through the initialization API. Have a look at https://github.com/mulesoft/api-notebook/blob/master/src/index.html#L16-L40 and https://github.com/mulesoft/api-notebook/blob/master/src/scripts/plugins/raml-client-generator/inject-api-keys.js#L10-L22. I'm not sure how setting client id and secret relates to having this as a standalone application, but yes, it can be used as a standalone application fine. There's example in this repo as standalone (it's always embedded in a frame and initialized by the JS API though) and there's an example in the wild being using at api-notebook.com.

**Comment by takearun** [comment]
Hi Blake,

Thank your for the response. Yes, I have already exposed it as a Webapp. 
As you mentioned, it just required a grunt build. Thank you so much.

Perhaps I am not asking my question right. 
I was trying to see how API exposers like me (not Developers) could define my API in a RAML and host API Notebook as a Webapp so that I can direct my Developers there to kickstart.

I am just getting my head around it, very happy that you helped me expose it as a webapp, thank you. 
I will dig around a bit more. 

I am going to mark this as closed. Thank you so much.

Thanks,
Arun

**Comment by blakeembrey** [comment]
You can set the notebook to initialise with a specific content, e.g. your RAML client, if that's what you're asking. Most of it's through obscure runtime options though, so apologies for that.

**Comment by takearun** [comment]
Hi Blake,

What I am really looking for is the "View live portal" mode of anypoint.mulesoft.com.
(https://anypoint.mulesoft.com/apiplatform/ladbrokes-2/#/portals/apis/16210/versions/17269/pages/32613)
All the API Notebooks I have defined, appears as a modify/play only mode.
I would like to expose such a webapp.

So that my Developers can see the examples and understand how to use my API.

Thanks,
Arun

**Comment by blakeembrey** [comment]
Gotcha. That's just the notebook running in it's default mode (non-embedded). To set up something like this too, check out https://github.com/mulesoft/api-notebook/blob/master/src/embedded.html. You can pass the notebook as content in the options. You can also just use the version hosted on api-notebook.com, just do something like:

```html
<script src="https://api-notebook.anypoint.mulesoft.com/scripts/embed.js" data-notebook="el-id" data-content="hello world">
```

You can also use the programmatic API shown in the above link.

**Comment by takearun** [comment]
Hi Blake,

Looks like embedded.html is always trying to contact github to access notebook.md.
I would like notebook.md stored locally and accessed every time I load embedded.html.
That way I don't need an active github account to display my notebooks.
Is that possible?
If so, can you please describe how to do that.

Really appreciate your help.

Thanks,
Arun

**Comment by blakeembrey** [comment]
@takearun In your case then, you can't just use `embedded.html` out of the box. You should remove the plugins that aren't required. For example, persistence, from the notebook initialization (https://github.com/mulesoft/api-notebook/blob/master/src/embedded.html#L22-L41).
