### ISSUE TITLE
get is not a function

### ISSUE THREAD

**Issue by vathalloor** [mulesoft/api-notebook#381]
I wrote a simple API for device interface and created a client using notebook. here is the link to API designer:
https://anypoint.mulesoft.com/apiplatform/uoit/admin/#/organizations/327e778d-697d-4e38-9536-8f181829bcd5/dashboard/apis/24067/versions/25583/designer#request_Devices_DeviceModel

But then, could not use the "get()" function as it says "get function is not defined". here is the link to notebook:
https://anypoint.mulesoft.com/apiplatform/uoit/admin/#/organizations/327e778d-697d-4e38-9536-8f181829bcd5/dashboard/apis/24067/versions/25583/portal/pages/39673/edit.

if anyone could please help me out.

Thanks.

**Comment by blakeembrey** [comment]
I can't access either of those links to look at it. I'm happy to help if you can provide me an example. Are you sure you're using the correct properties/methods?

**Comment by sichvoge** [comment]
Can't do anything on here either. And without a response I am afraid that we can't do anything. I am closing that for now as invalid to clean up the issues a bit. If there is still a problem and we get more information, I am happy to open it again.
