### ISSUE TITLE
Install dependencies with "npm install" fails because of missing "esprima-six"

### ISSUE THREAD

**Issue by hanneslehmann** [mulesoft/api-notebook#384]
Hello,

just cloned the project and tried to make an "npm install" which fails with following error:

Any possibility to get this up and running?

5159 error Linux 3.16.0-4-amd64
5160 error argv "node" "/usr/local/bin/npm" "install"
5161 error node v0.10.29
5162 error npm  v3.5.2
5163 error code E404
5164 error 404 Registry returned 404 for GET on https://registry.npmjs.org/espri
ma-six
5165 error 404
5166 error 404 'esprima-six' is not in the npm registry.
5167 error 404 You should bug the author to publish it (or use the name yourself
!)
5168 error 404 It was specified as a dependency of 'derequire'
5169 error 404 Note that you can also install from a
5170 error 404 tarball, folder, http url, or git url.
5171 verbose exit [ 1, true ]

**Comment by blakeembrey** [comment]
Odd, do you have any more information? It installs for me and definitely exists in the registry too. Perhaps your cache or network had issues?

**Comment by hanneslehmann** [comment]
I think the package is not in the repository any more. I didn't find it by manual looking at https://npmjs.org either. There is only esprima-six-legacy....?

**Comment by blakeembrey** [comment]
You're right, looks like it was still in my cache - I thought NPM kept access to old versions because I still see the old versions in the registry. I'll look and see what's needed to make the project installable again.

**Comment by blakeembrey** [comment]
Ok, just pushed a version to `master` with changes to remove this dependency.

**Comment by hanneslehmann** [comment]
Hi! Thanks, that solved the problem!

Now I have to figure out, why my browser is not showing anything ;)

Regards
