### ISSUE TITLE
Could not parse response: Unexpected string

### ISSUE THREAD

**Issue by unsown** [mulesoft/api-notebook#385]
Error example:
https://anypoint.mulesoft.com/apiplatform/unsown/#/portals/organizations/4d9cfd73-0b9b-4fa3-920c-52ab8ede1ea4/apis/47985/versions/49764/pages/62506

I imported the Jukebox API code to API Designer. Then run the same notebook code given in the tutorial, instead, using the mocking service generated by the imported version. Got the "Could not parse response: Unexpected string" error at the end of the script. 

I noticed the http response is the same as that sent by the service used in the tutorial.

**Comment by blakeembrey** [comment]
It looks like there's a syntax error in the response:

```json
  "artist": {
    "artistId": "110e8300-e32b-41d4-a716-664400445500"
    "artistName": "Daft Punk",
```

Note the missing comma after the `artistId` value. This could certainly use a better error message, but please let me know if there's any other issues.
