### ISSUE TITLE
TypeError: fs.readFile is not a function error when attempting to create API client

### ISSUE THREAD

**Issue by cskradski** [mulesoft/api-notebook#392]
I have installed API Notebook on my local machine.  When attempting to create a API client for the example raml file \build\test\fixtures\example.raml I receive an error.

API create client call:

API.createClient('example', '/test/fixtures/example.raml');

Error:

JS-YAML: TypeError: fs.readFile is not a function

Any help would be much appreciated!

**Comment by cskradski** [comment]
Some more context on error

JS-YAML: TypeError: fs.readFile is not a function at http://localhost:3000/plugins/raml-client-generator.js:150065:23

**Comment by nmarinel01** [comment]
Hi @cskradski !
When you create an API client call, second parameters is an url. I tried the following and it worked ok for me.

`API.createClient('example', 'http://localhost:3000/test/fixtures/example.raml');`

Hope this helps
Regards

**Comment by cskradski** [comment]
Your solution works for me as well.  Thanks so much!
